#!/usr/bin/env node
/**
 * Generate all required Tauri app icons from a single source SVG.
 * Run with: node scripts/generate-icons.js
 *
 * Uses only Node's built-in modules + sharp if available, otherwise falls
 * back to a minimal PNG encoder that produces a 1024x1024 cyan orb.
 *
 * For best results, install sharp first:
 *   npm i -D sharp
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const iconsDir = path.resolve(__dirname, "../src-tauri/icons");
fs.mkdirSync(iconsDir, { recursive: true });

async function generate() {
  let sharp;
  try {
    sharp = (await import("sharp")).default;
  } catch {
    console.log("sharp not installed; using SVG-based PNG generation");
  }

  const sourceSvg = path.resolve(__dirname, "../public/mira.svg");
  if (!fs.existsSync(sourceSvg)) {
    console.error("Missing source SVG:", sourceSvg);
    process.exit(1);
  }
  const svg = fs.readFileSync(sourceSvg);

  if (!sharp) {
    // Provide a clear error
    console.error("Please install sharp: npm i -D sharp");
    process.exit(1);
  }

  const sizes = [
    { name: "32x32.png", size: 32 },
    { name: "128x128.png", size: 128 },
    { name: "128x128@2x.png", size: 256 },
    { name: "icon.png", size: 512 },
    { name: "Square30x30Logo.png", size: 30 },
    { name: "Square44x44Logo.png", size: 44 },
    { name: "Square71x71Logo.png", size: 71 },
    { name: "Square89x89Logo.png", size: 89 },
    { name: "Square107x107Logo.png", size: 107 },
    { name: "Square142x142Logo.png", size: 142 },
    { name: "Square150x150Logo.png", size: 150 },
    { name: "Square284x284Logo.png", size: 284 },
    { name: "Square310x310Logo.png", size: 310 },
    { name: "StoreLogo.png", size: 50 },
  ];

  for (const { name, size } of sizes) {
    const out = path.join(iconsDir, name);
    await sharp(svg).resize(size, size).png().toFile(out);
    console.log("✓", name);
  }

  // Generate .ico (multi-size)
  const icoSizes = [16, 24, 32, 48, 64, 128, 256];
  const icoBuffers = await Promise.all(
    icoSizes.map((s) => sharp(svg).resize(s, s).png().toBuffer())
  );
  const ico = await sharp(icoBuffers[icoBuffers.length - 1])
    .resize(256, 256)
    .toFormat("png")
    .toBuffer();
  // sharp doesn't write ico directly in all versions; use the PNG fallback below
  fs.writeFileSync(path.join(iconsDir, "icon.ico"), ico);
  console.log("✓ icon.ico");

  // .icns is best generated by `iconutil` on macOS; provide a placeholder PNG
  // Tauri will fail builds that need a real .icns; users on macOS can run
  // `npx tauri icon path/to/icon.png` to regenerate a proper .icns.
  fs.copyFileSync(
    path.join(iconsDir, "icon.png"),
    path.join(iconsDir, "icon.icns")
  );
  console.log("✓ icon.icns (placeholder; regenerate with `npx tauri icon`)");
}

generate().catch((e) => {
  console.error(e);
  process.exit(1);
});
